-- Synchronize the single Super Admin bootstrap password with the documented
-- test/development credential. The hash is generated by better-auth/crypto.
UPDATE "account" AS credential
SET "password" = 'db19aaa34172fe30f9d70ad076e726b7:b6cee228cf78a282434ddaf5575935ce74ebeb729cc726cfc625ce94d4991fe55d473b9869d13b5a8696c2d66b4ca7fe38948de2ac21716c2544f4c343e1a3ce',
    "updated_at" = now()
FROM "user" AS primary_user
WHERE credential."user_id" = primary_user."id"
  AND credential."provider_id" = 'credential'
  AND lower(primary_user."email") = 'monai.yut@student.mahidol.edu';
